### ISSUE TITLE
mousio.etcd4j hangs

### ISSUE THREAD

**Issue by wayerr** [codeabovelab/haven-platform#20]
```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:261)
	  at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:189)
	  at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:58)
	  at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:59)
...below strings repeated many times....
	  at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:59)
	  at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:59)
	  at com.codeabovelab.dm.cluman.ds.kv.etcd.EtcdClientWrapper.set(EtcdClientWrapper.java:155)
	  at com.codeabovelab.dm.common.kv.mapping.NodeMapping.save(NodeMapping.java:84)
	  at com.codeabovelab.dm.common.kv.mapping.KvClassMapper.save(KvClassMapper.java:115)
	  at com.codeabovelab.dm.common.kv.mapping.KvMap$ValueHolder.flush(KvMap.java:172)
	  at com.codeabovelab.dm.common.kv.mapping.KvMap.flush(KvMap.java:461)
	  at com.codeabovelab.dm.cluman.ds.clusters.AbstractNodesGroup.flush(AbstractNodesGroup.java:136)
	  at com.codeabovelab.dm.cluman.ds.clusters.AbstractNodesGroup.updateAcl(AbstractNodesGroup.java:245)
	  at com.codeabovelab.dm.cluman.ds.clusters.DiscoveryStorageImpl.init(DiscoveryStorageImpl.java:142)
```
Investigation shows that promise losing response from server and hang on wait it

**Comment by wayerr** [comment]
```
Caused by: java.io.IOException: null
	at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:74)
	at com.codeabovelab.dm.cluman.ds.kv.etcd.EtcdClientWrapper.get(EtcdClientWrapper.java:138)
```
it not hang, but mean that both result and error is null
