### ISSUE TITLE
haven-agent.py fatal error

### ISSUE THREAD

**Issue by ZloyRabadaber** [codeabovelab/haven-platform#33]
I am use ubuntu server 16.04
start haven-agent.py

console log:

2017-03-02 00:38:06,459 - INFO - Configs: /etc/haven-agent.ini
Arguments: {'timeout': 10, 'log_level': 2, 'docker': '$SELF_IP:2375', 'secret': None, 'master': '$MASTER_IP:8761'}
2017-03-02 00:38:06,460 - WARNING - Run as daemon
2017-03-02 00:38:06,493 - ERROR - Cannot connect to Docker {'data': None, 'method': 'GET', 'docker': '$SELF_IP:2375', 'path': '/info'} due to error: [Errno -2] Name or service not known
2017-03-02 00:38:06,494 - ERROR - Cannot update registration due to [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/bin/haven-agent.py", line 167, in update
    info = docker.info()
  File "/usr/bin/haven-agent.py", line 83, in info
    return copy.deepcopy(self.__info.get())
  File "/usr/bin/haven-agent.py", line 38, in get
    self.__data = self.__loader(*args, **kwargs)
  File "/usr/bin/haven-agent.py", line 50, in <lambda>
    self.__info = CachedValue(loader=lambda: self.__send("/info"),
  File "/usr/bin/haven-agent.py", line 64, in __send
    self.conn.request(method, path)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
^CTraceback (most recent call last):
  File "/usr/bin/haven-agent.py", line 449, in <module>
    main()
  File "/usr/bin/haven-agent.py", line 445, in main
    time.sleep(bs.timeout)

help me pls

**Comment by ZloyRabadaber** [comment]
I think this is broblem:
clusret-store not work in docker swarm mode

**Comment by wayerr** [comment]
Quote from our doc:

>Step 1: Define the common variables for configuration needed in the scripts and configuration files. Feel free to set them as environment variables or replace them in the script:
> IP of master instance
> MASTER_IP=172.31.0.3
> IP of current configured node. This IP must be accessible from master instance
> SELF_IP=172.31.0.12

And you have:

>Arguments: {'timeout': 10, 'log_level': 2, 'docker': '$SELF_IP:2375', 'secret': None, 'master': '$MASTER_IP:8761'}

It is mean that you do not change both placeholders to concrete ip.

**Comment by ZloyRabadaber** [comment]
now:

docker info

`
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: box-3261
ID: Q534:IXSO:BHOA:S522:FI2U:MGBE:YQH6:SB55:BN5U:2WBC:ITHN:AY3Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Cluster Store: etcd://185.185.71.4:2379/dn
Cluster Advertise: 185.185.71.4:2375
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

haven-agent.py

`
2017-03-02 19:25:31,091 - INFO - Configs: /etc/haven-agent.ini
Arguments: {'log_level': 2, 'timeout': 10, 'secret': None, 'docker': '185.185.71.4:2375', 'master': '185.185.71.4:8761'}
2017-03-02 19:25:31,091 - WARNING - Run as daemon
2017-03-02 19:25:31,096 - ERROR - Cannot connect to Docker {'method': 'GET', 'path': '/info', 'data': None, 'docker': '185.185.71.4:2375'} due to error: [Errno 111] Connection refused
2017-03-02 19:25:31,096 - ERROR - Cannot update registration due to [Errno 111] Connection refused
Traceback (most recent call last):
  File "./haven-agent.py", line 167, in update
    info = docker.info()
  File "./haven-agent.py", line 83, in info
    return copy.deepcopy(self.__info.get())
  File "./haven-agent.py", line 38, in get
    self.__data = self.__loader(*args, **kwargs)
  File "./haven-agent.py", line 50, in <lambda>
    self.__info = CachedValue(loader=lambda: self.__send("/info"),
  File "./haven-agent.py", line 64, in __send
    self.conn.request(method, path)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
^CTraceback (most recent call last):
  File "./haven-agent.py", line 449, in <module>
    main()
  File "./haven-agent.py", line 445, in main
    time.sleep(bs.timeout)
KeyboardInterrupt
`

**Comment by ZloyRabadaber** [comment]
fixed. I am idiot. thx very much.
